In [1]:
import pandas as pd

In [3]:
bitcoin = pd.read_csv('data/bitcoin-hourly-ohclv-dataset/btc_hourly_ohclv_ta.csv')

In [4]:
bitcoin['dt'] = pd.to_datetime(bitcoin['DATETIME'])
bitcoin.head(1)

,UNIX_TIMESTAMP,DATETIME,OPEN,HIGH,CLOSE,LOW,VOLUME,SMA_20,EMA_12,EMA_26,...,VOLUME_SMA,MFI,ATR,PRICE_CHANGE,HIGH_LOW_RATIO,CLOSE_OPEN_RATIO,VOLATILITY_30D,PRICE_VOLATILITY_30D,HL_VOLATILITY_30D,dt
0,1418623200,2014-12-15 06:00:00.000,349.78,350.07,349.54,348.81,287499.35,348.784,348.845388,348.741338,...,202156.2935,41.596185,1.917314,-0.000686,1.003612,0.999314,0.036548,13.498893,0.009256,2014-12-15 06:00:00

In [5]:
!pip install plotly

Requirement already satisfied: plotly in c:\users\james\appdata\local\programs\python\python310\lib\site-packages (6.5.0)
Requirement already satisfied: narwhals>=1.15.1 in c:\users\james\appdata\local\programs\python\python310\lib\site-packages (from plotly) (2.12.0)
Requirement already satisfied: packaging in c:\users\james\appdata\local\programs\python\python310\lib\site-packages (from plotly) (25.0)

[notice] A new release of pip is available: 25.2 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [6]:
# def make_data(df):
    
thing = bitcoin.loc[bitcoin.DATETIME.str.startswith('2015-12-15')]

In [7]:
import plotly.graph_objects as go


fig = go.Figure(data=[go.Candlestick(x=thing['DATETIME'],
                open=thing['OPEN'],
                high=thing['HIGH'],
                low=thing['LOW'],
                close=thing['CLOSE'])])

In [8]:
fig.show()

In [9]:
bitcoin['date'] = bitcoin['dt'].dt.date

In [10]:
dfs_by_date = {d: sub_df for d, sub_df in bitcoin.groupby("date")}

In [11]:
df_dict = {}
count = 0 
for i in dfs_by_date:

    df_new = bitcoin.loc[bitcoin.date == i,:]
    df_dict[count] = df_new
    count +=1

In [12]:
df_dict

{0:     UNIX_TIMESTAMP                 DATETIME    OPEN    HIGH   CLOSE     LOW  \
 0       1418623200  2014-12-15 06:00:00.000  349.78  350.07  349.54  348.81
 1       1418626800  2014-12-15 07:00:00.000  349.54  351.10  345.20  344.74
 2       1418630400  2014-12-15 08:00:00.000  345.20  348.67  345.81  345.62
 3       1418634000  2014-12-15 09:00:00.000  345.81  348.25  347.97  347.39
 4       1418637600  2014-12-15 10:00:00.000  347.97  347.71  346.98  346.08
 5       1418641200  2014-12-15 11:00:00.000  346.98  347.58  347.41  346.30
 6       1418644800  2014-12-15 12:00:00.000  347.41  347.70  346.37  345.35
 7       1418648400  2014-12-15 13:00:00.000  346.37  347.52  346.78  345.70
 8       1418652000  2014-12-15 14:00:00.000  346.78  346.14  345.64  344.78
 9       1418655600  2014-12-15 15:00:00.000  345.64  347.34  346.51  345.21
 10      1418659200  2014-12-15 16:00:00.000  346.51  347.46  347.39  346.30
 11      1418662800  2014-12-15 17:00:00.000  347.39  346.91  346.73  345.61
 12      1418666400  2014-12-15 18:00:00.000  346.73  347.53  346.83  346.72
 13      1418670000  2014-12-15 19:00:00.000  346.83  347.70  347.29  346.83
 14      1418673600  2014-12-15 20:00:00.000  347.29  347.57  347.18  346.10
 15      1418677200  2014-12-15 21:00:00.000  347.18  347.70  346.66  346.01
 16      1418680800  2014-12-15 22:00:00.000  346.66  346.69  345.40  344.89
 17      1418684400  2014-12-15 23:00:00.000  345.40  346.22  345.21  344.30

        VOLUME    SMA_20      EMA_12      EMA_26  ...        MFI       ATR  \
 0   287499.35  348.7840  348.845388  348.741338  ...  41.596185  1.917314
 1   247473.50  348.5805  348.284559  348.479017  ...  40.323525  2.234648
 2   198309.01  348.4490  347.903858  348.281312  ...  40.289160  2.322888
 3   329161.73  348.3890  347.914033  348.258252  ...  40.582033  2.331253
 4   302615.83  348.2780  347.770336  348.163566  ...  30.875389  2.299735
 5   305061.33  348.2595  347.714900  348.107747  ...  30.988769  2.226897
 6   310522.99  348.1925  347.507992  347.979025  ...  30.670339  2.235690
 7   304756.62  348.1885  347.395993  347.890208  ...  38.853687  2.205998
 8   409477.70  348.1775  347.125840  347.723526  ...  30.043689  2.191284
 9   381001.61  348.0555  347.031096  347.633635  ...  38.881418  2.186906
 10  529704.29  347.8585  347.086312  347.615588  ...  49.023671  2.113556
 11  448903.68  347.6155  347.031495  347.549989  ...  46.461335  2.089730
 12  379000.82  347.4970  347.000495  347.496656  ...  51.792070  1.998321
 13  298652.46  347.4280  347.045035  347.481349  ...  53.423385  1.917727
 14  449113.57  347.2900  347.065798  347.459026  ...  51.681103  1.885746
 15  595682.74  347.1600  347.003368  347.399839  ...  48.249500  1.871764
 16  474664.07  347.0015  346.756696  347.251703  ...  45.845514  1.866638
 17  349285.80  346.8660  346.518743  347.100466  ...  39.733850  1.870450

     PRICE_CHANGE  HIGH_LOW_RATIO  CLOSE_OPEN_RATIO  VOLATILITY_30D  \
 0      -0.000686        1.003612          0.999314        0.036548
 1      -0.012416        1.018449          0.987584        0.036613
 2       0.001767        1.008825          1.001767        0.036592
 3       0.006246        1.002476          1.006246        0.036459
 4      -0.002845        1.004710          0.997155        0.036461
 5       0.001239        1.003696          1.001239        0.036450
 6      -0.002994        1.006805          0.997006        0.036453
 7       0.001184        1.005265          1.001184        0.036424
 8      -0.003287        1.003945          0.996713        0.036069
 9       0.002517        1.006170          1.002517        0.036064
 10      0.002540        1.003350          1.002540        0.036067
 11     -0.001900        1.003761          0.998100        0.036016
 12      0.000288        1.002336          1.000288        0.036014
 13      0.001326        1.002508          1.001326        0.035978
 14     -0.000317        1.004247          0.999683        0.035968
 15     -0.001498        1.004884          0.998502        0.035948
 16     -0.003635        1.005219          0.996365        0.035899
 17     -0.000550        1.005577          0.999450        0.035837

     PRICE_VOLATILITY_30D  HL_VOLATILITY_30D                  dt        date
 0              13.498893           0.009256 2014-12-15 06:00:00  2014-12-15
 1              13.488846           0.009276 2014-12-15 07:00:00  2014-12-15
 2              13.468585           0.009277 2014-12-15 08:00:00  2014-12-15
 3              13.463480           0.009252 2014-12-15 09:00:00  2014-12-15
 4              13.462040           0.009248 2014-12-15 10:00:00  2014-12-15
 5              13.463875           0.009239 2014-12-15 11:00:00  2014-12-15
 6              13.466330           0.009239 2014-12-15 12:00:00  2014-12-15
 7              13.474098           0.009223 2014-12-15 13:00:00  2014-12-15
 8              13.498930           0.009181 2014-12-15 14:00:00  2014-12-15
 9              13.522708           0.009165 2014-12-15 15:00:00  2014-12-15
 10             13.544475           0.009149 2014-12-15 16:00:00  2014-12-15
 11             13.569172           0.009128 2014-12-15 17:00:00  2014-12-15
 12             13.593384           0.009109 2014-12-15 18:00:00  2014-12-15
 13             13.615036           0.009091 2014-12-15 19:00:00  2014-12-15
 14             13.637675           0.009078 2014-12-15 20:00:00  2014-12-15
 15             13.659973           0.009070 2014-12-15 21:00:00  2014-12-15
 16             13.681423           0.009059 2014-12-15 22:00:00  2014-12-15
 17             13.706978           0.009044 2014-12-15 23:00:00  2014-12-15

 [18 rows x 30 columns],
 1:     UNIX_TIMESTAMP                 DATETIME    OPEN    HIGH   CLOSE     LOW  \
 18      1418688000  2014-12-16 00:00:00.000  345.21  344.96  343.91  342.98
 19      1418691600  2014-12-16 01:00:00.000  343.91  345.36  345.33  343.41
 20      1418695200  2014-12-16 02:00:00.000  345.33  345.95  342.34  340.89
 21      1418698800  2014-12-16 03:00:00.000  342.34  343.43  340.65  338.22
 22      1418702400  2014-12-16 04:00:00.000  340.65  340.38  339.23  336.69
 23      1418706000  2014-12-16 05:00:00.000  339.23  340.83  339.24  336.45
 24      1418709600  2014-12-16 06:00:00.000  339.24  339.67  338.97  337.01
 25      1418713200  2014-12-16 07:00:00.000  338.97  339.74  339.15  336.24
 26      1418716800  2014-12-16 08:00:00.000  339.15  341.11  334.35  333.07
 27      1418720400  2014-12-16 09:00:00.000  334.35  335.59  334.62  332.25
 28      1418724000  2014-12-16 10:00:00.000  334.62  335.36  330.85  330.55
 29      1418727600  2014-12-16 11:00:00.000  330.85  334.62  333.12  328.10
 30      1418731200  2014-12-16 12:00:00.000  333.12  335.38  334.57  331.64
 31      1418734800  2014-12-16 13:00:00.000  334.57  334.39  332.05  331.32
 32      1418738400  2014-12-16 14:00:00.000  332.05  334.98  334.69  331.46
 33      1418742000  2014-12-16 15:00:00.000  334.69  338.54  335.25  333.44
 34      1418745600  2014-12-16 16:00:00.000  335.25  336.04  335.12  333.43
 35      1418749200  2014-12-16 17:00:00.000  335.12  336.67  336.02  334.82
 36      1418752800  2014-12-16 18:00:00.000  336.02  335.94  334.07  333.27
 37      1418756400  2014-12-16 19:00:00.000  334.07  335.17  333.97  332.34
 38      1418760000  2014-12-16 20:00:00.000  333.97  334.04  331.60  330.43
 39      1418763600  2014-12-16 21:00:00.000  331.60  332.90  331.53  330.83
 40      1418767200  2014-12-16 22:00:00.000  331.53  332.62  331.88  331.00
 41      1418770800  2014-12-16 23:00:00.000  331.88  334.89  331.49  331.28

        VOLUME    SMA_20      EMA_12      EMA_26  ...        MFI       ATR  \
 18  292727.05  346.7295  346.117398  346.864135  ...  39.823096  1.896132
 19  292985.59  346.5070  345.996260  346.750495  ...  39.668915  1.899980
 20  364397.67  346.1470  345.433758  346.423792  ...  39.310339  2.125695
 21  464643.42  345.9195  344.697795  345.996104  ...  32.928847  2.346003
 22  358842.83  345.5905  343.856596  345.494911  ...  33.263460  2.461288
 23  464479.78  345.1540  343.146351  345.031584  ...  34.117936  2.598339
 24  455263.02  344.7535  342.503835  344.582578  ...  25.237157  2.602744
 25  412328.23  344.3405  341.987860  344.180165  ...  25.445118  2.666833
 26  405310.72  343.7395  340.812805  343.452004  ...  18.619843  3.050631
 27  501419.50  343.1315  339.860066  342.797782  ...  12.864243  3.071300
 28  590172.99  342.3920  338.473902  341.912761  ...  12.611405  3.195493
 29  416719.02  341.7225  337.650225  341.261445  ...  13.045995  3.432958
 30  494041.40  341.0815  337.176344  340.765783  ...  21.364909  3.454889
 31  515460.10  340.3475  336.387676  340.120169  ...  20.830355  3.440254
 32  573525.85  339.7405  336.126495  339.717934  ...  28.955760  3.445951
 33  719974.29  339.1385  335.991649  339.386976  ...  33.372660  3.564097
 34  737373.76  338.5355  335.857549  339.070904  ...  31.667227  3.495947
 35  904884.42  338.0035  335.882542  338.844911  ...  41.852362  3.378379
 36  815520.05  337.4370  335.603689  338.491214  ...  39.493667  3.333495
 37  795348.70  336.8750  335.352352  338.156309  ...  32.323191  3.297531
 38  852876.08  336.2595  334.775067  337.670657  ...  30.894451  3.319850
 39  614841.10  335.5695  334.275826  337.215793  ...  30.227124  3.230575
 40  498332.85  335.0465  333.907238  336.820549  ...  35.423394  3.115534
 41  459586.35  334.5885  333.535355  336.425694  ...  40.694662  3.150853

     PRICE_CHANGE  HIGH_LOW_RATIO  CLOSE_OPEN_RATIO  VOLATILITY_30D  \
 18     -0.003766        1.005773          0.996234        0.035832
 19      0.004129        1.005678          1.004129        0.035836
 20     -0.008658        1.014843          0.991342        0.035868
 21     -0.004937        1.015404          0.995063        0.035879
 22     -0.004169        1.010960          0.995831        0.035884
 23      0.000029        1.013018          1.000029        0.035807
 24     -0.000796        1.007893          0.999204        0.035753
 25      0.000531        1.010409          1.000531        0.035721
 26     -0.014153        1.024139          0.985847        0.035809
 27      0.000808        1.010053          1.000808        0.035808
 28     -0.011267        1.014552          0.988733        0.035798
 29      0.006861        1.019872          1.006861        0.035756
 30      0.004353        1.011277          1.004353        0.035754
 31     -0.007532        1.009266          0.992468        0.035773
 32      0.007951        1.010620          1.007951        0.035604
 33      0.001673        1.015295          1.001673        0.035597
 34     -0.000388        1.007828          0.999612        0.035597
 35      0.002686        1.005525          1.002686        0.035589
 36     -0.005803        1.008012          0.994197        0.035604
 37     -0.000299        1.008515          0.999701        0.035456
 38     -0.007096        1.010925          0.992904        0.035477
 39     -0.000211        1.006257          0.999789        0.035477
 40      0.001056        1.004894          1.001056        0.035477
 41     -0.001175        1.010897          0.998825        0.035478

     PRICE_VOLATILITY_30D  HL_VOLATILITY_30D                  dt        date
 18             13.736550           0.009029 2014-12-16 00:00:00  2014-12-16
 19             13.761982           0.009024 2014-12-16 01:00:00  2014-12-16
 20             13.794164           0.009031 2014-12-16 02:00:00  2014-12-16
 21             13.830795           0.009044 2014-12-16 03:00:00  2014-12-16
 22             13.870623           0.009052 2014-12-16 04:00:00  2014-12-16
 23             13.905492           0.009050 2014-12-16 05:00:00  2014-12-16
 24             13.935102           0.009038 2014-12-16 06:00:00  2014-12-16
 25             13.958289           0.009031 2014-12-16 07:00:00  2014-12-16
 26             13.994237           0.009046 2014-12-16 08:00:00  2014-12-16
 27             14.030287           0.009043 2014-12-16 09:00:00  2014-12-16
 28             14.087046           0.009040 2014-12-16 10:00:00  2014-12-16
 29             14.127574           0.009046 2014-12-16 11:00:00  2014-12-16
 30             14.166445           0.009047 2014-12-16 12:00:00  2014-12-16
 31             14.211010           0.009047 2014-12-16 13:00:00  2014-12-16
 32             14.258075           0.009031 2014-12-16 14:00:00  2014-12-16
 33             14.304588           0.009038 2014-12-16 15:00:00  2014-12-16
 34             14.351011           0.009031 2014-12-16 16:00:00  2014-12-16
 35             14.392397           0.009025 2014-12-16 17:00:00  2014-12-16
 36             14.439730           0.009032 2014-12-16 18:00:00  2014-12-16
 37             14.477544           0.009018 2014-12-16 19:00:00  2014-12-16
 38             14.521483           0.009018 2014-12-16 20:00:00  2014-12-16
 39             14.565867           0.009012 2014-12-16 21:00:00  2014-12-16
 40             14.608833           0.009008 2014-12-16 22:00:00  2014-12-16
 41             14.652670           0.009011 2014-12-16 23:00:00  2014-12-16

 [24 rows x 30 columns],
 2:     UNIX_TIMESTAMP                 DATETIME    OPEN    HIGH   CLOSE     LOW  \
 42      1418774400  2014-12-17 00:00:00.000  331.49  332.75  329.97  326.65
 43      1418778000  2014-12-17 01:00:00.000  329.97  336.73  334.45  330.11
 44      1418781600  2014-12-17 02:00:00.000  334.45  334.46  333.29  331.36
 45      1418785200  2014-12-17 03:00:00.000  333.29  333.59  331.78  330.67
 46      1418788800  2014-12-17 04:00:00.000  331.78  332.66  331.98  330.73
 47      1418792400  2014-12-17 05:00:00.000  331.98  332.58  330.92  329.57
 48      1418796000  2014-12-17 06:00:00.000  330.92  331.62  329.34  327.97
 49      1418799600  2014-12-17 07:00:00.000  329.34  328.88  326.80  326.04
 50      1418803200  2014-12-17 08:00:00.000  326.80  328.91  327.08  326.14
 51      1418806800  2014-12-17 09:00:00.000  327.08  330.03  326.12  323.58
 52      1418810400  2014-12-17 10:00:00.000  326.12  324.99  323.12  321.66
 53      1418814000  2014-12-17 11:00:00.000  323.12  325.11  320.59  318.77
 54      1418817600  2014-12-17 12:00:00.000  320.59  322.18  319.04  315.57
 55      1418821200  2014-12-17 13:00:00.000  319.04  321.18  319.15  316.76
 56      1418824800  2014-12-17 14:00:00.000  319.15  321.34  319.31  318.07
 57      1418828400  2014-12-17 15:00:00.000  319.31  319.81  319.19  317.45
 58      1418832000  2014-12-17 16:00:00.000  319.19  320.65  318.53  317.51
 59      1418835600  2014-12-17 17:00:00.000  318.53  320.78  317.20  315.33
 60      1418839200  2014-12-17 18:00:00.000  317.20  318.01  316.35  315.35
 61      1418842800  2014-12-17 19:00:00.000  316.35  318.92  318.04  315.13
 62      1418846400  2014-12-17 20:00:00.000  318.04  321.16  320.28  317.27
 63      1418850000  2014-12-17 21:00:00.000  320.28  321.14  320.50  319.09
 64      1418853600  2014-12-17 22:00:00.000  320.50  324.52  322.73  319.55
 65      1418857200  2014-12-17 23:00:00.000  322.73  323.49  320.02  319.00

         VOLUME    SMA_20      EMA_12      EMA_26  ...        MFI       ATR  \
 42   539104.22  334.1255  332.986839  335.947494  ...  40.944506  3.361507
 43   606751.37  333.8860  333.211941  335.836569  ...  46.733609  3.604256
 44   585206.03  333.6020  333.223950  335.647934  ...  40.912812  3.568238
 45   595684.46  333.2335  333.001804  335.361420  ...  40.565240  3.521935
 46   654953.54  333.1150  332.844603  335.110945  ...  34.107223  3.408226
 47   574040.29  332.9300  332.548510  334.800504  ...  26.819006  3.379781
 48   696294.49  332.8545  332.054893  334.396023  ...  26.971558  3.399082
 49   530623.33  332.5385  331.246448  333.833354  ...  17.789574  3.392005
 50   509483.52  332.1640  330.605456  333.333106  ...  24.369898  3.347576
 51   652994.28  331.8675  329.915386  332.798802  ...  24.829823  3.569178
 52   749477.44  331.2890  328.869942  332.081853  ...  25.202104  3.632808
 53  1233385.61  330.5560  327.596105  331.230605  ...  23.540562  3.826179
 54  2480512.40  329.7520  326.279781  330.327597  ...  14.723728  4.025023
 55   694464.64  328.9085  325.182892  329.499627  ...  16.344768  4.053236
 56   676092.95  328.1705  324.279370  328.744840  ...  22.087774  3.997290
 57   541281.06  327.4315  323.496390  328.037074  ...  16.681166  3.880341
 58  1006970.23  326.7780  322.732330  327.332846  ...  24.683872  3.827460
 59  1775230.63  326.0615  321.881202  326.582265  ...  22.486842  3.943355
 60   735291.71  325.2850  321.030248  325.824320  ...  22.402670  3.851687
 61   732665.99  324.6125  320.570210  325.247703  ...  27.745482  3.847281
 62  1147558.97  324.1280  320.525562  324.879725  ...  35.369173  3.850332
 63   508913.50  323.4305  320.521630  324.555301  ...  39.246711  3.721737
 64   905392.83  322.9025  320.861379  324.420094  ...  40.962563  3.810899
 65   702300.74  322.3145  320.731936  324.094161  ...  40.851132  3.859406

     PRICE_CHANGE  HIGH_LOW_RATIO  CLOSE_OPEN_RATIO  VOLATILITY_30D  \
 42     -0.004585        1.018674          0.995415        0.035241
 43      0.013577        1.020054          1.013577        0.035300
 44     -0.003468        1.009355          0.996532        0.035190
 45     -0.004531        1.008831          0.995469        0.035193
 46      0.000603        1.005836          1.000603        0.035045
 47     -0.003193        1.009133          0.996807        0.034985
 48     -0.004775        1.011129          0.995225        0.034995
 49     -0.007712        1.008711          0.992288        0.035021
 50      0.000857        1.008493          1.000857        0.034997
 51     -0.002935        1.019933          0.997065        0.034797
 52     -0.009199        1.010353          0.990801        0.034790
 53     -0.007830        1.019889          0.992170        0.034814
 54     -0.004835        1.020946          0.995165        0.034815
 55      0.000345        1.013954          1.000345        0.034761
 56      0.000501        1.010281          1.000501        0.034746
 57     -0.000376        1.007434          0.999624        0.034724
 58     -0.002068        1.009889          0.997932        0.034724
 59     -0.004175        1.017283          0.995825        0.034605
 60     -0.002680        1.008435          0.997320        0.034152
 61      0.005342        1.012027          1.005342        0.034163
 62      0.007043        1.012261          1.007043        0.034167
 63      0.000687        1.006425          1.000687        0.034162
 64      0.006958        1.015553          1.006958        0.034185
 65     -0.008397        1.014075          0.991603        0.034205

     PRICE_VOLATILITY_30D  HL_VOLATILITY_30D                  dt        date
 42             14.682312           0.009003 2014-12-17 00:00:00  2014-12-17
 43             14.688071           0.009007 2014-12-17 01:00:00  2014-12-17
 44             14.677480           0.008990 2014-12-17 02:00:00  2014-12-17
 45             14.676136           0.008981 2014-12-17 03:00:00  2014-12-17
 46             14.695185           0.008963 2014-12-17 04:00:00  2014-12-17
 47             14.704260           0.008960 2014-12-17 05:00:00  2014-12-17
 48             14.719019           0.008955 2014-12-17 06:00:00  2014-12-17
 49             14.742429           0.008955 2014-12-17 07:00:00  2014-12-17
 50             14.755147           0.008949 2014-12-17 08:00:00  2014-12-17
 51             14.740099           0.008941 2014-12-17 09:00:00  2014-12-17
 52             14.752004           0.008937 2014-12-17 10:00:00  2014-12-17
 53             14.769894           0.008953 2014-12-17 11:00:00  2014-12-17
 54             14.800483           0.008958 2014-12-17 12:00:00  2014-12-17
 55             14.844957           0.008955 2014-12-17 13:00:00  2014-12-17
 56             14.895192           0.008952 2014-12-17 14:00:00  2014-12-17
 57             14.936845           0.008948 2014-12-17 15:00:00  2014-12-17

In [13]:
daily = (
    bitcoin.sort_values("dt")
      .groupby("date")
      .agg(
          open_price=("OPEN", "first"),
          close_price=("CLOSE", "last")
      )
)

daily["next_open"] = daily["open_price"].shift(-1)
daily["next_close"] = daily["close_price"].shift(-1)
daily["diff"] = daily["next_close"] - daily["next_open"]
daily["up_indicator"] = (daily["diff"] > 0).astype(int)

In [14]:
ref_df = daily[["next_open", "next_close", "diff", "up_indicator"]].copy()
ref_df = ref_df.reset_index().rename(columns={"index": "day"})

In [15]:
ref_df.to_csv("reference_data.csv", index=False)

In [17]:
ref_df =  pd.read_csv('reference_data.csv')

In [18]:
ref_df

            date  next_open  next_close     diff  up_indicator
0     2014-12-15     345.21      331.49   -13.72             0
1     2014-12-16     331.49      320.02   -11.47             0
2     2014-12-17     320.02      310.96    -9.06             0
3     2014-12-18     310.96      317.70     6.74             1
4     2014-12-19     317.70      330.39    12.69             1
...          ...        ...         ...      ...           ...
3992  2025-11-19   91483.02    88067.49 -3415.53             0
3993  2025-11-20   86553.58    84237.34 -2316.24             0
3994  2025-11-21   85087.62    84696.98  -390.64             0
3995  2025-11-22   84696.98    84653.66   -43.32             0
3996  2025-11-23        NaN         NaN      NaN             0

[3997 rows x 5 columns]

In [ ]:
# now lets gt daily photos

In [19]:
import plotly.graph_objects as go
from PIL import Image
import matplotlib.pyplot as plt
import plotly.express as px

num_days = len(ref_df)

for i in range(3680,num_days):
  current_df = df_dict[i]
  fig = go.Figure(data=[go.Candlestick(x=current_df['DATETIME'],
                                       open=current_df['OPEN'],
                                       high=current_df['HIGH'],
                                       low=current_df['LOW'],
                                       close=current_df['CLOSE'])])

  fig.update_yaxes(dtick=20, showgrid=True, gridcolor="lightgray")
  fig.write_image(f"fig_{i}.png")